### ISSUE TITLE
Create: About Page-Our Founding

### ISSUE THREAD

**Issue by tugbacanbaz** [kogunlu/codezillas-capstone#15]
### Screenshot
![about page 1](https://user-images.githubusercontent.com/113346418/209482030-7e803e64-43ad-42ab-a365-0e12241c3fb9.png)

**Comment by tugbacanbaz** [comment]
Feat: About component and related founding picture added

**Comment by tugbacanbaz** [comment]
Style: background fixed columns recreated 

Couldn't commit in first try so I re-comitted so it looks like I only changed one number. Almost done,test needed.

**Comment by kogunlu** [comment]
@tugbacanbaz since we have completed, tested and merged this issue; closing it over here. Thank you again for your great work.
