### ISSUE TITLE
Create: Log In Page

### ISSUE THREAD

**Issue by tugbacanbaz** [kogunlu/codezillas-capstone#19]
### Important
1-We need to re-use our shared button component for the "Login" and "Submit" button. Button styles needs some changes according to the screenshot
2-We can take the icons from Footer page and change its style or take it from Sign Up page
3-For styling of the Card we can use tailwind style of previously created "Cards" component
4-We need to direct these information to Firebase
5-We can make sure that the mail adress is valid (optional)
6-We can make an alert message if email or password is empty (optional)

### Screenshot
![Log In](https://user-images.githubusercontent.com/113346418/209777051-89b7662a-7c81-43c2-8079-80f83618a925.png)

**Comment by kogunlu** [comment]
#32
