### ISSUE TITLE
Create: Booking Page

### ISSUE THREAD

**Issue by kogunlu** [kogunlu/codezillas-capstone#9]
# Need to create Booking Page according to the given screenshot

## Important

1. We need to create an object for each user and direct this information to Firebase

## Screenshots

![Image](https://user-images.githubusercontent.com/101986399/208924550-c9a6aa77-2370-4fa5-a1cf-dd42a184760f.png)

![Image](https://user-images.githubusercontent.com/101986399/208924565-379338b9-7009-4241-9c4d-b233b6979fdf.png)

![Image](https://user-images.githubusercontent.com/101986399/208924575-b6282053-ec71-45f5-8992-d747af724ea2.png)

![Image](https://user-images.githubusercontent.com/101986399/208924585-eef591b5-c868-4b35-8f05-8959026774ff.png)

![Image](https://user-images.githubusercontent.com/101986399/208924592-4f15dfb0-3157-4dd8-82d9-703664ca917e.png)

![Image](https://user-images.githubusercontent.com/101986399/208924603-28b0b294-556b-4046-8146-956866085018.png)

![Image](https://user-images.githubusercontent.com/101986399/208924617-3f5d0eef-c1ec-4c8a-aad9-df1b75265b60.png)

![Image](https://user-images.githubusercontent.com/101986399/208924625-99893eb4-8ec9-478a-9b22-bed0a4e7060f.png)

**Comment by kogunlu** [comment]
Cards created. Redux part done, firebase part in progress

**Comment by kogunlu** [comment]
Firebase part is done. Snapshot testing part required.

**Comment by kogunlu** [comment]
Testing part complete. Issue done.

**Comment by tugbacanbaz** [comment]
Firstly thank you for the hard work Kuday. I will share my review with you. Your code is working wonderfully, I only have somethings to share considering the style of the page and some misspellings.

In this part we have a misspelling "Therapy". It was written wrong in Figma too so I am not sure if we should change it.
<img width="451" alt="image" src="https://user-images.githubusercontent.com/113346418/209978103-11ded8e1-e1a5-4497-abef-c1fb91b63e36.png">

There shouldn't be a "*" at the end.
<img width="464" alt="image" src="https://user-images.githubusercontent.com/113346418/209978414-814b3012-5268-45e0-b209-e6645d7921b2.png">

This part the arrangement was different in Figma. 4th one was Non-religious. Figma has same selection for 3rd and 5th. I think our one is better for selection but if we copy this site maybe we should match it.
<img width="286" alt="image" src="https://user-images.githubusercontent.com/113346418/209978877-9c986b48-e7e8-4768-8b17-3097cb94f2e0.png">

Two lines of paragraphs needed to match the style.
<img width="360" alt="image" src="https://user-images.githubusercontent.com/113346418/209979323-9c845f2f-cfe7-4565-85cf-9549f86a9ed6.png">

Needs a dot after the text.
<img width="510" alt="image" src="https://user-images.githubusercontent.com/113346418/209979436-f46b0edd-579d-49b4-829b-bc5caf7d04e2.png">

In submit part it should say "all"
<img width="524" alt="image" src="https://user-images.githubusercontent.com/113346418/209980343-6007416d-9ef6-41f3-8875-e28248f3746e.png">

Thank you again, hope my review will be helpfull.
